### ISSUE TITLE
BY-14  As a user, I want additional information about each building. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#15]
Information such as phone number, address, and faculty is displayed when the user clicks on a building. 

Related to issue #14

**Comment by jaychenblue** [comment]
Isn't this BY-10?

**Comment by vincentcerri** [comment]
The final design should resemble this mockup:
![building information mockup.PNG](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/dd2cc592-b142-4327-93eb-e91536d13e88)

Here is the checklist of features that should be included for this issue to be considered completed:

- [ ] Building label shown on the outline of the building (e.g "H" and "LB" shown in the mockup)
- [ ] Menu that appears as an overlay when the building is clicked on

In the menu there should be the following features:
- [ ] name of the building
- [ ] an explore inside button
- [ ] a "Get There" button, 
- [ ] The hours that the building is open

*** once these features have been completed, this issue can be moved to the "In Review" board. ***

**Comment by vincentcerri** [comment]
Here is a progress report of how the layout is turning out. 
We have the information windows reading the information about the buildings from a file. 
We have markers that are clickable for each building. 
The name of the building is shown.
The menu appears when the marker is clicked on.

Whats next to do is to format the window nicely so that we can display all the information. We also need to change the markers to custom icons that we will use for each building. We need to add the buttons onto to the pop up windows. We are reading the information from a text file that we will encrypt. 

![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/629dd3ef-d580-4d39-ae59-e4405d9763ae)

**Comment by vincentcerri** [comment]
Progress report: 
- Added the explore inside button.
- encrypted the file
- added the building hours
- All we are missing is a few labels for the buildings and then this issue will be completed.

![image.png](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/4b349820-46bf-48fa-9d43-032fce8ab6aa)
