### ISSUE TITLE
 BY-17 As a user, I want the application to be displayed in the language of my device, if it is set to English or French.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#17]
The language of the application is set based on the language of the user’s phone.
Related to issues #18 , #19

**Comment by JenYn** [comment]
There is not really a mockup that we can base ourselves off of since this is mainly related to backend implementation.

**To do for this feature:**
- [ ] Research how to detect the device's default language
- [ ] Have the application launch in the default language
- [ ] Ensure that once the user changes the language, the language of the application does not switch back to the default 

**Acceptance criteria**:
- [ ] The application launches in the default language of the device
- [ ] If we close the application and change the default language of the device, it will change to match the new default language

**Comment by 13rinda** [comment]
This issue seems to overlap with the closed issue [#108] due to the fact that the default language of Android Studio is already English, and the implemented code to add French as a second language has already changed the relevant fields to the French language. What requires to be implemented for this current issue has already been implemented with issue [#108}, for this reasoning, this issue will be closed.
