### ISSUE TITLE
BY-18  As a user, I want to be able to change the language of the application between French and English. 

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#18]
The application can be displayed in either French or English, which the user can set in the settings.

**Comment by 13rinda** [comment]
In order for the user to switch from viewing the application in English or French, he or she needs to have a button available for them to switch between both languages. Once the button is implemented and the backend work connecting the switch of the button to its appropriate language is successfully implemented, the following acceptance test may be verified. 

Acceptance Test:
-While the mobile phone remains in the English setting, the application button is pressed in order to switch languages to the French language.
-While the phone remains in the French setting, the application button is pressed to switch languages to the English language.

Test passing Criteria:
The application is displayed to the switched language as intended by the user. This is to say if the user switched to the French language then the application, including all its related buttons should be displayed in French, and vice versa for the switch to the English button.

**Comment by JenYn** [comment]
The users will be able to select the language of the application in the menu:
![Mockups Final Final-35](https://user-images.githubusercontent.com/26283932/75612088-7b906b80-5aee-11ea-8a12-114dc800bcf6.png)

**Comment by jaychenblue** [comment]
By the end of sprint 4, the entire application should be entirely translated to French.

**Comment by JenYn** [comment]
After consulting with the product owner, we came to an agreement that displaying the application in the language of the user's phone is enough and that a user would not want to display the application in a different language than the one their phone is set to.
