### ISSUE TITLE
BY-47   As a developer, I want to demonstrate to the product owner that we can display the app in the device’s default language.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#19]
As a developer, I need to demonstrate to the product owner that we are able to implement a feature where the default language of the application will be English if the phone is set to any other language than English or French.

**Comment by 13rinda** [comment]
Since English is the default language to Android already, English did not need to be set to b default. However, if the user has his or her phone set to the French language then this application should display in the French language. This means that all the buttons should be also displayed in French. As of right now, we do not have any buttons needing translations as the current buttons which are implemented are the names of places such as Layola (name of the campus). Therefore it would not make sense to translate this to a French translation. However, to test that the implementation is performing successfully the following acceptance test was performed:

-The setting from the mobile device was changed to french 

Acceptance test criteria met as the button was displayed with a FRENCH title before the title as seen by the bellow snapshot taken after running the code:

 
<img width="309" alt="Screen Shot 2020-02-28 at 10 48 09 PM" src="https://user-images.githubusercontent.com/31190776/75600518-346a9200-5a7e-11ea-8878-7baf2aabda02.png">


For this feature to work successfully a french value file was created, it will later be updated after the buttons requiring translation are implemented. The French title on the "Layola" button was removed before pushing this working code as it was not a requirement to change this specific button. What is displayed in the screenshot was for testing purposes.

**Comment by jaychenblue** [comment]
Why was this story closed without opening a pull request and merging to master? Reopened.
