### ISSUE TITLE
Modify the search bar to search for Concordia indoor and outdoor specific locations. 

### ISSUE THREAD

**Issue by vincentcerri** [jaychenblue/scout-concordia#83]
This is a continuation of BY-58 [#81].

When using the search bar to search for Concordia buildings or rooms, if google maps cannot find the specified room, our application should still point you to the correct room. 

Here is the checklist of features that should be included for this issue to be considered completed:
- [x] Can search for room numbers at SGW campus
- [x] Can search for room numbers at Loyola campus
- [x] Can search for any Concordia building at SGW campus
- [x] Can search for any Concordia building at Loyola campus
- [x] When searching for Concordia buildings (eg. H Building), we want the app to automatically know that we are talking about Concordia. 

*** once these features have been completed, this issue can be moved to the "In Review" board.

**Comment by JenYn** [comment]
This issue is mainly back-end implementation, therefore there is not really a visual representation for it. However, this mockup demonstrates that we can search for a specific class room in the hall building, which is recognized by the search bar. 
![Mockups Final Final-18 (2)](https://user-images.githubusercontent.com/26283932/75612217-91526080-5aef-11ea-8947-c4b61183591e.png)

**Comment by jaychenblue** [comment]
I believe @ManpreetSohal has already started working on this.

@13rinda and @SeifElDerby were assigned to come up with a solution involving regex. Please update if there's been any progress on this issue.
